### ISSUE TITLE
Invalid FiniteGroups.block_decomposition function

### ISSUE THREAD

**Issue by physzzy** [jayren3996/FiniteGroups.jl#1]
The point group reducible representation satisfies the group multiplication at a precision of 10**-10. But the block_decomposition function seems to give the wrong results.

I attached a python code that could reproduce the wrong results.

In the code, _'PG_WingerD_Reps'_ is a 676-dimensional reducible representation of C3i, and the _PG_Winger_D_deccom_ are some  irreducible representation which is decomposed from  _'PG_WingerD_Reps'_. But all two-dimensional representations in _PG_Winger_D_deccom_ seem irreducible.

[issue.zip](https://github.com/jayren3996/FiniteGroups.jl/files/7833472/issue.zip)

**Comment by jayren3996** [comment]
The error was caused by the complex data type of the irreps. Previously, for a given irrep of type `Vector{Matrix{T}}`, the reality of `T` was used to identify the reality of the representation (if the argument `R=true` and the irrep is complex, the function returns a real projection to the real irreps). However, when all irreps are calculated by function `irreps`, the real and complex representation coincide and Julia promote the output array to be of type `Vector{Vector{Matrix{ComplexF64}}}`, which further cause the reality ambiguity.

In this update, the imaginary part of the irreps are explicitly checked before invoking the real-irrep algorithm.
